version: '3.9'

services:
  api:
    build:
      dockerfile: ./Dockerfile
      target: api
    environment:
      - PORT=8080
      - SWAGGER=true
      - JWT_SECRET=${JWT_SECRET:?error}
      - DATABASE_USERNAME=${DATABASE_USERNAME:?error}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD:?error}
      - DATABASE_DBNAME=${DATABASE_DBNAME:?error}
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - KAFKA_BROKERS=kafka:9092
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - 8080:8080
    depends_on:
      kafka:
        condition: service_healthy
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - default
      - kafka-net
  log-consumer:
    build:
      dockerfile: ./Dockerfile
      target: log-consumer
    environment:
      - JWT_SECRET=${JWT_SECRET:?error}
      - DATABASE_USERNAME=${DATABASE_USERNAME:?error}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD:?error}
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_DBNAME=${DATABASE_DBNAME:?error}
      - KAFKA_BROKERS=kafka:9092
    depends_on:
      kafka:
        condition: service_healthy
      db:
        condition: service_healthy
    networks:
      - default
      - kafka-net
