version: '3.9'

# Infra overrides for Dev env

services:
  redis:
    restart: always
    ports:
      - 6379:6379
    env_file: &env
      - path: './.env'
        required: false
  db:
    restart: always
    ports:
      - '${DATABASE_PORT-5432}:5432'
    env_file: *env
  zookeeper:
    ports:
      - '2181:2181'
  kafka:
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: 'api-log:1:1'
    ports:
      - 9093:9093
  kafka2:
    ports:
      - 9094:9093
    image: wurstmeister/kafka
    container_name: kafka2
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka2:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

    networks:
      - kafka-net
