version: '3.9'

# Dev Compose File

include:
  - path:
      - compose.infra.yaml
  - path:
      - compose.app.yaml
      - compose.app.prod.yaml

services:
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $HOME/.docker/config.json:/config.json
    command: --interval 300
