version: '3.9'

services:
  redis:
    image: redis:7-alpine3.20
    restart: always
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379
    env_file: &env
      - path: './.env'
        required: false
  db:
    image: postgres:16.4-alpine3.20
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '${DATABASE_PORT-5432}:5432'
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME:?error}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:?error}
      POSTGRES_DB: ${DATABASE_DBNAME:?error}
    env_file: *env
  kafka:
    image: apache/kafka
    ports:
      - 9092:9092
    # env_file: *env
volumes:
  db-data:
  redis-data:
